# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SemanticSegmentation
                                 A QGIS plugin
 This plugin lets you create segmentation from aerial images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-04
        copyright            : (C) 2026 by Kelian Pons
        email                : kelian.pons@centrale.centralelille.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SemanticSegmentation class from file SemanticSegmentation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .semantic_segmentation import SemanticSegmentation
    return SemanticSegmentation(iface)
