# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SemanticSegmentation
                                 A QGIS plugin
 This plugin lets you create segmentation from aerial images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Kelian Pons
        email                : kelian.pons@centrale.centralelille.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, pyqtSignal
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction, QCheckBox, QTreeWidgetItem, QInputDialog, QTableWidgetItem, QMessageBox, QFileDialog

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .semantic_segmentation_dialog import SemanticSegmentationDialog,InstallDialog
from .install_env import get_micromamba, setup_flair_environment
from .utils import *

import subprocess
import processing
import random
import json
import re
import os
import yaml
import shutil
import numpy as np
from osgeo import gdal
from qgis.core import QgsProject, QgsTask, QgsApplication, QgsMessageLog, Qgis, QgsPalettedRasterRenderer
from qgis.gui import QgsColorButton

class SemanticSegmentation:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        self.temp_dir = os.path.join(self.plugin_dir,"temp")
        self.group_config_dir = os.path.join(self.plugin_dir,"group_config")
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SemanticSegmentation_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Semantic Segmentation')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SemanticSegmentation', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/semantic_segmentation/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Segmentation'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&Semantic Segmentation'),
                action)
            self.iface.removeToolBarIcon(action)
    
    def check_env(self):
        """Check if the virtual environment for flair is installed"""
        env_dir = os.path.join(self.plugin_dir,"flair_env")

        if os.name == 'nt':                                         #for windows
            python_exe = os.path.join(env_dir, "python.exe")
        else:                                                       #for mac linux
            python_exe = os.path.join(env_dir, "bin", "python")
            
        if os.path.exists(python_exe):
            return True
        else:
            return False

    def update_install_progress(self, value):
        if self.install_dlg.progress_bar != None:
            self.install_dlg.progress_bar.setValue(value)
    
    def update_install_log(self, message): 
        if self.install_dlg.journal_install != None:
            self.install_dlg.journal_install.append(message)

    def show_installation_dialog(self):
        self.install_dlg = InstallDialog()
        
        self.install_dlg.progress_bar.setRange(0, 100)
        self.install_dlg.progress_bar.setVisible(False)
        self.install_dlg.install_button.clicked.connect(self.start_installation_task)
        
        result = self.install_dlg.exec_()
        
        if result == 1:
            self.iface.messageBar().pushMessage("Success", "Environment ready. You can now use the plugin.", level=0)
            return True
        else:
            self.iface.messageBar().pushMessage("Error", "Installation failed. Check QGIS messages log.", level=2)
            return False

    def start_installation_task(self):
        self.install_dlg.install_button.setEnabled(False)
        self.install_dlg.progress_bar.setVisible(True)
        
        self.install_task = InstallEnv("Installing Conda Env...", self.plugin_dir, self.install_dlg)
        self.install_task.log_signal.connect(self.update_install_log)
        self.install_task.progress_signal.connect(self.update_install_progress)
        QgsApplication.taskManager().addTask(self.install_task)
    


    def add_group(self,group_name=None, color_hex=None):
        text, ok_pressed = QInputDialog.getText(self.dlg, "Nouveau Groupe", "Entrer un nom de groupe")

        if ok_pressed:
            if text:
                existing_items = self.dlg.treeWidget.findItems(text, Qt.MatchExactly | Qt.MatchRecursive, 0)
                
                if len(existing_items) > 0:
                    QMessageBox.warning(self.dlg, "Erreur", "Ce nom de groupe existe déjà")
                    return
                treeitem = QTreeWidgetItem(self.dlg.treeWidget)
                treeitem.setText(0, text)
                treeitem.setData(0, Qt.UserRole, text)                
                
                # Allow dropping items inside this global class
                treeitem.setFlags(Qt.ItemIsEnabled | Qt.ItemIsSelectable | Qt.ItemIsDropEnabled | Qt.ItemIsEditable)
                treeitem.setExpanded(True)
                
                row_index = self.dlg.tableWidget.rowCount()
                self.dlg.tableWidget.insertRow(row_index)
                
                tableitem1 = QTableWidgetItem(text)
                tableitem1.setData(Qt.UserRole, text)
                self.dlg.tableWidget.setItem(row_index, 0, tableitem1)

                color_button = QgsColorButton()
                color_button.setAllowOpacity(False)
                color_button.setColor(QColor(random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)))
                                
                self.dlg.tableWidget.setCellWidget(row_index, 1, color_button)

    def make_group_color_dict(self):
        group_config = {}
        row_count = self.dlg.tableWidget.rowCount()
        
        for row in range(row_count):
            item_name = self.dlg.tableWidget.item(row, 0)
            
            if item_name != None:
                group_name = item_name.text()
                
                color_widget = self.dlg.tableWidget.cellWidget(row, 1)
                group_color = "#FFFFFF" 
                
                if color_widget != None:
                    group_color = color_widget.color().name()
                    
                group_config[group_name] = {
                    "color": group_color,
                    "classes": []
                }
                
        tree_root = self.dlg.treeWidget.invisibleRootItem()
        item_count = tree_root.childCount()
        
        for i in range(item_count):
            tree_item = tree_root.child(i)
            item_name = tree_item.text(0)
            
            if item_name in group_config:
                class_count = tree_item.childCount()
                
                for j in range(class_count):
                    base_class_item = tree_item.child(j)
                    base_class_name = base_class_item.text(0)
                    group_config[item_name]["classes"].append(base_class_name)
                    
            if item_name not in group_config:
                group_config[item_name] = {
                    "color": get_color(item_name.lower().replace(" ", "_"),os.path.join(self.plugin_dir,"color.clr")),
                    "classes": [item_name]
                }
                    
        with open(os.path.join(self.temp_dir,"group_config_temp.json"), "w", encoding="utf-8") as f:
            json.dump(group_config, f, ensure_ascii=False, indent=4)

        return group_config
                    
    def remove_group(self):
        selected_items = self.dlg.treeWidget.selectedItems()
        
        for item in selected_items:
            if not (item.flags() & Qt.ItemIsEditable):
                continue
            item_text = item.text(0)
            parent = item.parent()
            tree_root = self.dlg.treeWidget.invisibleRootItem()
            
            if parent == None:
                child_count = item.childCount()
                
                for i in range(child_count - 1, -1, -1):
                    child = item.takeChild(i)
                    tree_root.addChild(child)
                    
                tree_root.removeChild(item)
            
            if parent != None:
                parent.removeChild(item)
                tree_root.addChild(item)

            self.remove_from_table_by_text(item_text)
      
    def remove_from_table_by_text(self, text):
        row_count = self.dlg.tableWidget.rowCount()
        
        for row in range(row_count - 1, -1, -1):
            item = self.dlg.tableWidget.item(row, 0)
            
            if item != None:
                if item.text() == text:
                    item_table = self.dlg.tableWidget.item(row, 0)
                    if item_table != None:
                        item_text = item_table.text()
                        self.dlg.tableWidget.removeRow(row)
                        
                        tree_items = self.dlg.treeWidget.findItems(item_text, Qt.MatchExactly | Qt.MatchRecursive, 0)
                        
                        for tree_item in tree_items:
                            self.delete_tree_item(tree_item)
    
    def on_tree_item_changed(self, item, column):
        new_text = item.text(0)
        old_text = item.data(0, Qt.UserRole)
        
        if old_text == None:
            return
            
        if new_text == old_text:
            return
            
        existing_items = self.dlg.treeWidget.findItems(new_text, Qt.MatchExactly | Qt.MatchRecursive, 0)
        
        if len(existing_items) > 1:
            QMessageBox.warning(self.dlg, "Erreur", "Ce nom de groupe existe déjà")
            self.dlg.treeWidget.blockSignals(True)
            item.setText(0, old_text)
            self.dlg.treeWidget.blockSignals(False)
            return
            
        row_count = self.dlg.tableWidget.rowCount()
        
        for row in range(row_count):
            table_item = self.dlg.tableWidget.item(row, 0)
            
            if table_item != None:
                if table_item.text() == old_text:
                    self.dlg.tableWidget.blockSignals(True)
                    table_item.setText(new_text)
                    table_item.setData(Qt.UserRole, new_text) 
                    self.dlg.tableWidget.blockSignals(False)
                    
        item.setData(0, Qt.UserRole, new_text)

    def on_table_item_changed(self, item):
        if item.column() != 0:
            return
            
        new_text = item.text()
        old_text = item.data(Qt.UserRole)
        
        if old_text == None:
            return
            
        if new_text == old_text:
            return
            
        matching_items = self.dlg.tableWidget.findItems(new_text, Qt.MatchExactly)
        matching_tree = self.dlg.treeWidget.findItems(new_text, Qt.MatchExactly | Qt.MatchRecursive, 0)
        
        if len(matching_items) > 1:
            QMessageBox.warning(self.dlg, "Erreur", "Ce nom de groupe existe déjà")
            self.dlg.tableWidget.blockSignals(True)
            item.setText(old_text)
            self.dlg.tableWidget.blockSignals(False)
            return
    
        if len(matching_tree) > 0:
            QMessageBox.warning(self.dlg, "Erreur", "Ce nom de groupe existe déjà")
            self.dlg.tableWidget.blockSignals(True)
            item.setText(old_text)
            self.dlg.tableWidget.blockSignals(False)
            return
            
        tree_items = self.dlg.treeWidget.findItems(old_text, Qt.MatchExactly | Qt.MatchRecursive, 0)
        
        for tree_item in tree_items:
            self.dlg.treeWidget.blockSignals(True)
            tree_item.setText(0, new_text)
            tree_item.setData(0, Qt.UserRole, new_text)
            self.dlg.treeWidget.blockSignals(False)
            
        item.setData(Qt.UserRole, new_text)

    def sync_table_to_tree_selection(self):
        self.dlg.treeWidget.blockSignals(True)
        self.dlg.treeWidget.clearSelection()
        
        selected_items = self.dlg.tableWidget.selectedItems()
        
        for item in selected_items:
            if item.column() == 0:
                group_name = item.text()
                tree_items = self.dlg.treeWidget.findItems(group_name, Qt.MatchExactly | Qt.MatchRecursive, 0)
                
                for tree_item in tree_items:
                    tree_item.setSelected(True)
                    
        self.dlg.treeWidget.blockSignals(False)

    def sync_tree_to_table_selection(self):
        self.dlg.tableWidget.blockSignals(True)
        self.dlg.tableWidget.clearSelection()
        
        selected_items = self.dlg.treeWidget.selectedItems()
        
        for item in selected_items:
            group_name = item.text(0)
            table_items = self.dlg.tableWidget.findItems(group_name, Qt.MatchExactly)
            
            for table_item in table_items:
                row = table_item.row()
                self.dlg.tableWidget.selectRow(row)
                
        self.dlg.tableWidget.blockSignals(False)

    def save_group_config(self):
        file_path, _ = QFileDialog.getSaveFileName(
            self.dlg, 
            "Sauvegarder une configuration", 
            self.group_config_dir, 
            "JSON Files (*.json)"
        )
        
        if file_path:
            config_data = self.make_group_color_dict()
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(config_data, f, ensure_ascii=False, indent=4)

    def load_group_config(self):
        file_path, _ = QFileDialog.getOpenFileName(
            self.dlg, 
            "Charger une configuration", 
            self.group_config_dir, 
            "JSON Files (*.json)"
        )
        
        if not file_path:
            return
            
        with open(file_path, "r", encoding="utf-8") as f:
            config_data = json.load(f)
            
        base_items = {}
        all_items = self.dlg.treeWidget.findItems("", Qt.MatchContains | Qt.MatchRecursive, 0)
        
        # Extract existing base classes to reuse them
        for item in all_items:
            if item.childCount() == 0:
                if not (item.flags() & Qt.ItemIsEditable):
                    base_items[item.text(0)] = item.clone()
                    
        self.dlg.treeWidget.clear()
        self.dlg.tableWidget.setRowCount(0)
        
        tree_root = self.dlg.treeWidget.invisibleRootItem()
        
        for group_name, data in config_data.items():
            classes = data.get("classes", [])
            color_hex = data.get("color", "#FFFFFF")
            
            is_base_class = False
            
            if len(classes) == 1:
                if classes[0] == group_name:
                    is_base_class = True
                    
            if is_base_class == True:
                if group_name in base_items:
                    tree_root.addChild(base_items[group_name])
            
            if is_base_class == False:
                treeitem = QTreeWidgetItem(self.dlg.treeWidget)
                treeitem.setText(0, group_name)
                treeitem.setData(0, Qt.UserRole, group_name)
                treeitem.setFlags(Qt.ItemIsEnabled | Qt.ItemIsSelectable | Qt.ItemIsDropEnabled | Qt.ItemIsEditable)
                treeitem.setExpanded(True)
                
                row_index = self.dlg.tableWidget.rowCount()
                self.dlg.tableWidget.insertRow(row_index)
                
                tableitem = QTableWidgetItem(group_name)
                tableitem.setData(Qt.UserRole, group_name)
                self.dlg.tableWidget.setItem(row_index, 0, tableitem)
                
                color_button = QgsColorButton()
                color_button.setAllowOpacity(False)
                color_button.setColor(QColor(color_hex))
                self.dlg.tableWidget.setCellWidget(row_index, 1, color_button)
                
                for class_name in classes:
                    if class_name in base_items:
                        treeitem.addChild(base_items[class_name])

    def on_task_completed(self):
        clear_temp_directory(self.temp_dir)
        self.dlg.text_edit_journal.append("FINISHED")
        QMessageBox.information(self.dlg, "Terminé", "Segmentation Terminée")
        self.dlg.accept()

    def on_task_terminated(self):
        clear_temp_directory(self.temp_dir)
        self.dlg.text_edit_journal.append("TASK FAILED OR CANCELED")
        QMessageBox.warning(self.dlg, "Erreur", "Voir le journal pour plus d'informations")

    def generate_vrt(self,layer,band,output_name):
        if layer != None and band >0:
            self.dlg.text_edit_journal.append(f"Creation of VRT for {band} : {output_name}...")
            QCoreApplication.processEvents()
            vrt_r = os.path.join(self.temp_dir, output_name)
            
            params_r ={
                'INPUT': layer.source(),
                'EXTRA': f'-b {band}',
                'OUTPUT': vrt_r
            }
            
            processing.run("gdal:translate", params_r)
            return vrt_r

    def update_log_ui(self, message):
            if self.dlg.text_edit_journal != None:
                self.dlg.text_edit_journal.append(message)
    
    def update_progress_ui(self, value):
        if self.dlg.progressBar != None:
            self.dlg.progressBar.setValue(value)

    def run_prediction(self):
        self.dlg.tabWidget.setCurrentIndex(1)
        self.dlg.text_edit_journal.append("Execution started...")
        self.update_progress_ui(0)

        extracted_vrts = []

        layer_r = self.dlg.layer_combo_red.currentLayer()
        band_r = self.dlg.band_combo_red.currentBand()
        layer_g = self.dlg.layer_combo_green.currentLayer()
        band_g = self.dlg.band_combo_green.currentBand()
        layer_b = self.dlg.layer_combo_blue.currentLayer()
        band_b = self.dlg.band_combo_blue.currentBand()
        layer_i = self.dlg.layer_combo_nir.currentLayer()
        band_i = self.dlg.band_combo_nir.currentBand()
        
        vrt_r = self.generate_vrt(layer_r,band_r,"temp_r.vrt")
        vrt_g = self.generate_vrt(layer_g,band_g,"temp_g.vrt")
        vrt_b = self.generate_vrt(layer_b,band_b,"temp_b.vrt")
        vrt_i = self.generate_vrt(layer_i,band_i,"temp_i.vrt")
        if vrt_r != None :
            extracted_vrts.append(vrt_r)
        if vrt_g != None :
            extracted_vrts.append(vrt_g)
        if vrt_b != None :
            extracted_vrts.append(vrt_b)
        if vrt_i != None :
            extracted_vrts.append(vrt_i)

        if len(extracted_vrts) > 2:
            temp_vrt = os.path.join(self.temp_dir, "temp_stack.vrt")
            final_vrt = os.path.join(self.temp_dir, "final_stack.vrt")
            self.dlg.text_edit_journal.append("gdal:buildvirtualraster...")
            self.update_progress_ui(10)
            QCoreApplication.processEvents()

            params_stack = {
                'INPUT': extracted_vrts,
                'RESOLUTION': 1,
                'SEPARATE': True,
                'OUTPUT': temp_vrt
            }
            
            processing.run("gdal:buildvirtualraster", params_stack)
            if self.dlg.extent_widget.isValid():
                self.dlg.text_edit_journal.append("gdal:cliprasterbyextent...")
                QCoreApplication.processEvents()
                extent = self.dlg.extent_widget.outputExtent()
                extent_str = f"{extent.xMinimum()},{extent.xMaximum()},{extent.yMinimum()},{extent.yMaximum()}"
                params_emprise = {
                    'INPUT':temp_vrt,
                    'PROJWIN':extent_str,
                    'OUTPUT':final_vrt,
                }
                processing.run("gdal:cliprasterbyextent", params_emprise )
                input_img_path = final_vrt
            else:
                input_img_path = temp_vrt

        self.dlg.text_edit_journal.append("Preprocessing finished. Starting FLAIR...")
        self.update_progress_ui(20)
        QCoreApplication.processEvents()

        output_full_path = self.dlg.mQgsFileWidget.filePath()
        if output_full_path == "":
            QMessageBox.warning(self.dlg, "Error", "No output path specified")
            return
            
        if os.path.isdir(output_full_path) == True:
            output_full_path = os.path.join(output_full_path, "segmentation.tif")
            
        output_path = os.path.join(self.temp_dir)
        output_name = "segmentation"
        
        if vrt_i != None :
            model_path = os.path.join(self.plugin_dir, "vendor", "FLAIR-INC_rgbi_15cl_resnet34-unet_weights.pth")
            channels = [1,2,3,4]
            norm_means = [105.08, 110.87, 101.82, 106.38]
            norm_stds = [52.17, 45.38, 44.00, 39.69]
        else:
            model_path = os.path.join(self.plugin_dir, "vendor", "FLAIR-INC_rgb_15cl_resnet34-unet_weights.pth")
            channels = [1,2,3]
            norm_means = [105.08, 110.87, 101.82]
            norm_stds = [52.17, 45.38, 44]

        if self.dlg.ClassSelection.isChecked():
            selected_classes = []
            output_type_val = "class_prob"
            current_mode = "class_selection"
            check_boxes = self.dlg.ClassSelection.findChildren(QCheckBox)
            for cb in check_boxes:
                if not cb.isChecked():
                    formatted_name = cb.text().lower().replace(" ", "_")
                    selected_classes.append(formatted_name)
        else :  
            output_type_val = "argmax"
            current_mode = "group_creation"


        config = {
            "output_path": output_path,
            "output_name": output_name,
            "input_img_path": input_img_path,
            "channels": channels,
            "img_pixels_detection": 512,
            "margin": 128,
            "output_type": output_type_val,
            "n_classes": 19,
            "model_weights": model_path,
            "model_framework": {
                "model_provider": "SegmentationModelsPytorch",
                "SegmentationModelsPytorch": {"encoder_decoder": "resnet34_unet"}
            },
            "batch_size": 4, 
            "use_gpu": False, 
            "num_worker": 0,
            "write_dataframe": False,
            "norma_task": [{
                "norm_type": "custom",
                "norm_means": norm_means,
                "norm_stds": norm_stds
            }]
        }

        temp_yaml_path = os.path.join(self.temp_dir, "temp_config.yaml")
        with open(temp_yaml_path, 'w') as outfile:
            yaml.dump(config, outfile, default_flow_style=False)

        self.iface.messageBar().pushMessage("Success", f"Config saved: {temp_yaml_path}", level=0)

        env_dir = os.path.join(self.plugin_dir, "flair_env")
        python_exe = os.path.join(env_dir, "python.exe") if os.name == 'nt' else os.path.join(env_dir, "bin", "python3") # select the right python for windows of mac/linux
        script_path = os.path.join(self.plugin_dir, "vendor",'FLAIR-1', "src", "zone_detect", "main.py")
        
        if not os.path.exists(python_exe) or not os.path.exists(script_path):
            self.iface.messageBar().pushMessage("Error", "Python env or FLAIR script missing", level=2)
            return

        clr_file_path = os.path.join(self.plugin_dir, "color.clr")
        self.task = FlairInferenceTask(
            description="FLAIR Segmentation",
            python_exe=python_exe,
            script_path=script_path,
            yaml_path=temp_yaml_path,
            flair_out=os.path.join(output_path,f"{output_name}.tif"),
            temp_dir = self.temp_dir,
            output_tif=output_full_path,
            clr_path=clr_file_path,
            iface=self.iface,
            mode = current_mode,
            group_config = self.make_group_color_dict() if current_mode == "group_creation" else None,
            class_config = selected_classes if current_mode == "class_selection" else None,
            mask_layer= self.dlg.mask_layer.currentLayer() if self.dlg.mask_layer != None else None,
            plugin_dir = self.plugin_dir 
        )
        self.task.log_message_signal.connect(self.update_log_ui)
        self.task.progress_value_signal.connect(self.update_progress_ui)
        self.task.taskCompleted.connect(self.on_task_completed)
        self.task.taskTerminated.connect(self.on_task_terminated)
        
        QgsApplication.taskManager().addTask(self.task)
        self.iface.messageBar().pushMessage("Info", "Analysis started in background", level=0)



    def run(self):
        if not self.check_env():
            is_installed = self.show_installation_dialog()
            if not is_installed:
                return 

        self.dlg = SemanticSegmentationDialog()
        self.dlg.tabWidget.setCurrentIndex(0)
        self.dlg.extent_widget.setMapCanvas(self.iface.mapCanvas())
        self.dlg.extent_widget.clear()
        self.update_progress_ui(0)

        check_boxes = self.dlg.ClassSelection.findChildren(QCheckBox)

        for cb in check_boxes:
            cb.toggled.connect(lambda checked, current_cb=cb: toggle_strikethrough(checked, current_cb))

        self.dlg.ClassSelection.toggled.connect(
            lambda checked, other=self.dlg.GroupCreation: toggle_exclusive_groupboxes(checked, other))
        
        self.dlg.GroupCreation.toggled.connect(
            lambda checked, other=self.dlg.ClassSelection: toggle_exclusive_groupboxes(checked, other))

        # Connect the buttons to the functions
        self.dlg.btn_add.clicked.connect(self.add_group)
        self.dlg.btn_remove.clicked.connect(self.remove_group)
        self.dlg.treeWidget.itemChanged.connect(self.on_tree_item_changed)
        self.dlg.tableWidget.itemChanged.connect(self.on_table_item_changed)
        self.dlg.tableWidget.itemSelectionChanged.connect(self.sync_table_to_tree_selection)
        self.dlg.treeWidget.itemSelectionChanged.connect(self.sync_tree_to_table_selection)
        self.dlg.button_box.accepted.connect(self.run_prediction)
        self.dlg.btn_load.clicked.connect(self.load_group_config)
        self.dlg.btn_save.clicked.connect(self.save_group_config)
        
        if not self.dlg.exec_():
            return



class FlairInferenceTask(QgsTask):
    """Background task for FLAIR inference to keep QGIS responsive"""

    log_message_signal = pyqtSignal(str)
    progress_value_signal = pyqtSignal(int)

    def __init__(self, description, python_exe, script_path, yaml_path,flair_out,temp_dir, output_tif, clr_path,iface,mode,group_config,class_config,mask_layer,plugin_dir):
        super().__init__(description, QgsTask.CanCancel)
        self.python_exe = python_exe
        self.script_path = script_path
        self.yaml_path = yaml_path
        self.flair_out = flair_out
        self.temp_dir = temp_dir
        self.output_tif = output_tif
        self.iface = iface
        self.process = None
        self.clr_path = clr_path
        self.new_color = None
        self.mode = mode 
        self.group_config = group_config
        self.class_config = class_config
        self.mask_layer = mask_layer
        self.plugin_dir = plugin_dir

    def run(self):
        try:
            clean_env = os.environ.copy()
            
            if 'LD_LIBRARY_PATH' in clean_env:
                del clean_env['LD_LIBRARY_PATH']
            if 'PYTHONPATH' in clean_env:
                del clean_env['PYTHONPATH']
            if 'PYTHONHOME' in clean_env:
                del clean_env['PYTHONHOME']

            flair_root = os.path.dirname(os.path.dirname(os.path.dirname(self.script_path)))

            self.process = subprocess.Popen(
                [self.python_exe,"-u" ,"-m", "src.zone_detect.main", f"--conf={self.yaml_path}"],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1,
                cwd=flair_root,
                env=clean_env
            )

            for line in self.process.stdout:
                if self.isCanceled():
                    self.process.terminate()
                    return False
                match = re.search(r'(\d+)%', line.strip())
                if match == None:
                    self.log_message_signal.emit(line.strip())
                else:
                    progress = int(match.group(1))
                    self.progress_value_signal.emit(int(20 + (progress * 0.7)))


            self.process.wait()
            
            if self.process.returncode == 0:
                return True
            else:
                return False
        except Exception as error_msg:
            self.log_message_signal.emit(str(error_msg))
            return False
    
    def finished(self, result):
        self.log_message_signal.emit("Starting post processing...")
        
        if result == True:
            if self.mode == "group_creation":
                self.post_traitement_group_creation()
            elif self.mode == "class_selection":
                self.post_traitement_class_selection()
            self.progress_value_signal.emit(90)

            layer_name = os.path.basename(self.output_tif)
            layer = self.iface.addRasterLayer(self.output_tif, layer_name)
            
            if layer != None:
                if os.path.exists(self.new_color):
                    self.apply_color_palette(layer, self.new_color)
            
            self.progress_value_signal.emit(100)
            self.iface.messageBar().pushMessage("Success", "Inference complete", level=Qgis.Success)
            
        if result == False:
            self.iface.messageBar().pushMessage("Error", "Task failed", level=Qgis.Critical)

    def post_traitement_class_selection(self):
        self.new_color = os.path.join(self.temp_dir, "class_color.clr")
            
        name_to_index = {}
        original_clr_lines = {}
        
        with open(self.clr_path, 'r') as file:
            for line in file:
                parts = line.strip().split()
                
                if len(parts) >= 6:
                    index = int(parts[0])
                    name = parts[5].lower().replace(" ", "_")
                    name_to_index[name] = index
                    original_clr_lines[name] = line
                    
        selected_indices = []
        new_clr_lines = []
        
        for class_name in self.class_config:
            if class_name in name_to_index:
                original_index = name_to_index[class_name]
                selected_indices.append(original_index)
                new_clr_lines.append(original_clr_lines[class_name])
                
        with open(self.new_color, 'w') as file:
            file.writelines(new_clr_lines)
            
        ds = gdal.Open(self.flair_out)
        bands_data = []
        
        for idx in selected_indices:
            # GDAL bands are indexed starting form 1 flair index from 0
            band = ds.GetRasterBand(idx + 1)
            bands_data.append(band.ReadAsArray())
            
        stacked_data = np.stack(bands_data, axis=0)
        local_argmax = np.argmax(stacked_data, axis=0)
        
        final_data = np.zeros_like(local_argmax, dtype=np.uint8)
        
        for i in range(len(selected_indices)):
            original_idx = selected_indices[i]
            final_data[local_argmax == i] = original_idx

        
        #TODO Utiliser gdalwarp -overwrite -of GTiff -cutline pour appliquer la couche de masquage. 
        
        driver = gdal.GetDriverByName("GTiff")
            
        if self.mask_layer != None:
            current_out_path = os.path.join(self.temp_dir, "temp_unclipped.tif")
            
        if self.mask_layer == None:
            current_out_path = self.output_tif
            
        out_ds = driver.Create(current_out_path, ds.RasterXSize, ds.RasterYSize, 1, gdal.GDT_Byte)
        
        out_ds.SetProjection(ds.GetProjection())
        out_ds.SetGeoTransform(ds.GetGeoTransform())
        
        out_band = out_ds.GetRasterBand(1)
        out_band.WriteArray(final_data)
        out_band.FlushCache()
        
        out_ds = None
        ds = None

        if self.mask_layer != None:
            params_clip = {
                'INPUT': current_out_path,
                'MASK': self.mask_layer,
                'NODATA': 255,
                'CROP_TO_CUTLINE': False,
                'KEEP_RESOLUTION': True,
                'OUTPUT': self.output_tif
            }
            
            processing.run("gdal:cliprasterbymasklayer", params_clip)

            self.import_histogram()

        return None

    def post_traitement_group_creation(self):
        self.new_color = os.path.join(self.temp_dir, "group_color.clr")
        
        name_to_index = {}
        
        with open(self.clr_path, 'r') as file:
            for line in file:
                parts = line.strip().split()
                
                if len(parts) >= 6:
                    
                    index = int(parts[0])
                    name = parts[5].lower().replace(" ", "_")
                    name_to_index[name] = index
                    
        reclass_map = {}
        new_clr_lines = []
        
        for group_name, group_data in self.group_config.items():
            hex_color = group_data["color"].lstrip('#')
            classes = group_data["classes"]
            
            r = int(hex_color[0:2], 16)
            g = int(hex_color[2:4], 16)
            b = int(hex_color[4:6], 16)
            
            group_indices = []
            
            for class_name in classes:
                formatted_name = class_name.lower().replace(" ", "_")
                
                if formatted_name in name_to_index:
                    group_indices.append(name_to_index[formatted_name])
                    
            if len(group_indices) > 0:
                min_index = min(group_indices)
                
                for old_idx in group_indices:
                    reclass_map[old_idx] = min_index
                    
                formatted_group = group_name.lower().replace(" ", "_")
                new_clr_lines.append(f"{min_index} {r} {g} {b} 255 {formatted_group}\n")
                
        with open(self.new_color, 'w') as file:
            file.writelines(new_clr_lines)
            
        # Modification of the output prediction

        ds = gdal.Open(self.flair_out)
        band = ds.GetRasterBand(1)
        data = band.ReadAsArray()
        
        reclassified_data = np.copy(data)
        
        for old_val, new_val in reclass_map.items():
            if old_val != new_val:
                reclassified_data[data == old_val] = new_val
        
        #TODO Utiliser gdalwarp -overwrite -of GTiff -cutline pour appliquer la couche de masquage. 

        driver = gdal.GetDriverByName("GTiff")
            
        if self.mask_layer != None:
            current_out_path = os.path.join(self.temp_dir, "temp_unclipped.tif")
            
        if self.mask_layer == None:
            current_out_path = self.output_tif
            
        out_ds = driver.Create(current_out_path, ds.RasterXSize, ds.RasterYSize, 1, gdal.GDT_Byte)
        
        out_ds.SetProjection(ds.GetProjection())
        out_ds.SetGeoTransform(ds.GetGeoTransform())
        
        out_band = out_ds.GetRasterBand(1)
        out_band.WriteArray(reclassified_data)
        out_band.FlushCache()
        
        out_ds = None
        ds = None

        if self.mask_layer != None:
            params_clip = {
                'INPUT': current_out_path,
                'MASK': self.mask_layer,
                'NODATA': 255,
                'CROP_TO_CUTLINE': False,
                'KEEP_RESOLUTION': True,
                'OUTPUT': self.output_tif
            }
            
            processing.run("gdal:cliprasterbymasklayer", params_clip)

            self.import_histogram()

        return None

    def import_histogram(self):
        script_stats = os.path.join(self.plugin_dir, "generate_hist.py")
        
        cmd_stats = [
            self.python_exe,
            script_stats,
            self.output_tif,
            self.new_color,
            self.temp_dir
        ]
        
        subprocess.run(cmd_stats)


    def apply_color_palette(self, layer, final_clr):
        palette_classes = []
        
        with open(final_clr, 'r') as file:
            for line in file:
                parts = line.strip().split()
                if len(parts) >= 4:
                    pixel_value = int(parts[0])
                    red = int(parts[1])
                    green = int(parts[2])
                    blue = int(parts[3])
                    label = str(parts[-1])
                    color = QColor(red, green, blue)
                    palette_class = QgsPalettedRasterRenderer.Class(pixel_value, color, label)
                    palette_classes.append(palette_class)
        
        provider = layer.dataProvider()
        renderer = QgsPalettedRasterRenderer(provider, 1, palette_classes)
        layer.setRenderer(renderer)
        layer.setOpacity(0.5)
        layer.triggerRepaint()
        self.iface.layerTreeView().refreshLayerSymbology(layer.id())


class InstallEnv(QgsTask):
    log_signal = pyqtSignal(str)
    progress_signal = pyqtSignal(int)
    
    def __init__(self, description, plugin_dir, dialog):
        super().__init__(description, QgsTask.CanCancel)
        self.plugin_dir = plugin_dir
        self.dialog = dialog
        self.env_dir = os.path.join(self.plugin_dir,"flair_env")
        
    def run(self):
        try:
            mamba = get_micromamba(self.plugin_dir)
            setup_flair_environment(self.plugin_dir, mamba,self.env_dir,log_callback=self.log_signal.emit,progress_callback=self.progress_signal.emit)
            return True
        except Exception as e:
            QgsMessageLog.logMessage(f"Install failed: {e}", "FLAIR", Qgis.Critical)
            return False

    def finished(self,result):
        if result:
            self.dialog.accept() 
        else:
            self.dialog.reject()