# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SemanticSegmentation
                                 A QGIS plugin
 This plugin lets you create segmentation from aerial images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Kelian Pons
        email                : kelian.pons@centrale.centralelille.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .semantic_segmentation_dialog import SemanticSegmentationDialog
from .install_env import setup_flair_environment

import os.path
import os
import yaml
from qgis.core import QgsProject


class SemanticSegmentation:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SemanticSegmentation_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Semantic Segmentation')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SemanticSegmentation', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/semantic_segmentation/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Segmentation'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&Semantic Segmentation'),
                action)
            self.iface.removeToolBarIcon(action)

    def run_installation(self):
            """Launches the installation of the environment"""

            python_path = setup_flair_environment(self.plugin_dir)

            self.iface.messageBar().pushMessage(
                "Success", 
                "The FLAIR environment is ready!", 
                level=0, duration=5
            ) 

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = SemanticSegmentationDialog()
            self.dlg.pushButton_2.clicked.connect(self.run_installation)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            print("--- LE BOUTON OK A ÉTÉ CLIQUÉ ---")
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            layer_name = self.dlg.comboBox.currentText()
            
            # On cherche la vraie couche géographique dans QGIS grâce à son nom
            layers = QgsProject.instance().mapLayersByName(layer_name)
            if not layers:
                self.iface.messageBar().pushMessage("Erreur", "Couche introuvable", level=2)
                return
            
            # On extrait le chemin absolu du fichier sur le disque dur (.tif)
            input_img_path = layers[0].source()

            # 2. Récupérer le chemin de sortie
            output_full_path = self.dlg.lineEdit.text()
            if not output_full_path:
                self.iface.messageBar().pushMessage("Erreur", "Veuillez choisir un chemin de sortie", level=2)
                return
                
            output_path = os.path.dirname(output_full_path) + "/"
            output_name = os.path.basename(output_full_path)

            # 3. Chemin vers le modèle (On suppose qu'il est dans le dossier vendor)
            model_path = os.path.join(self.plugin_dir, "vendor", "FLAIR-INC_rgbi_15cl_resnet34-unet_weights.pth")

            # 4. Construction du dictionnaire de configuration (format attendu par FLAIR)
            config = {
                "output_path": output_path,
                "output_name": output_name,
                "input_img_path": input_img_path,
                "channels": [1, 2, 3, 4], # On suppose RVB + Infrarouge
                "img_pixels_detection": 512,
                "margin": 128,
                "output_type": "argmax",
                "n_classes": 19, # On garde 19 par défaut pour la V1
                "model_weights": model_path,
                "model_framework": {
                    "model_provider": "SegmentationModelsPytorch",
                    "SegmentationModelsPytorch": {
                        "encoder_decoder": "resnet34_unet"
                    }
                },
                "batch_size": 4, # Mettre 2 si l'ordinateur a peu de RAM
                "use_gpu": False, # On force le CPU pour le moment pour éviter les crashs CUDA
                "num_worker": 0,
                "write_dataframe": False,
                "norma_task": [
                    {
                        "norm_type": "custom",
                        "norm_means": [105.08, 110.87, 101.82, 106.38],
                        "norm_stds": [52.17, 45.38, 44.00, 39.69]
                    }
                ]
            }

            # 5. Écriture du fichier temporaire
            temp_yaml_path = os.path.join(self.plugin_dir, "temp_config.yaml")
            with open(temp_yaml_path, 'w') as outfile:
                yaml.dump(config, outfile, default_flow_style=False)
            
            self.iface.messageBar().pushMessage("Succès", f"Fichier de configuration créé : {temp_yaml_path}", level=0)
