# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SemanticSegmentation
                                 A QGIS plugin
 This plugin lets you create segmentation from aerial images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Kelian Pons
        email                : kelian.pons@centrale.centralelille.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .semantic_segmentation_dialog import SemanticSegmentationDialog,InstallDialog
from .install_env import setup_flair_environment

import subprocess
import os
import yaml
from qgis.core import QgsProject, QgsTask, QgsApplication, QgsMessageLog, Qgis, QgsPalettedRasterRenderer


class SemanticSegmentation:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SemanticSegmentation_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Semantic Segmentation')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SemanticSegmentation', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/semantic_segmentation/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Segmentation'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&Semantic Segmentation'),
                action)
            self.iface.removeToolBarIcon(action)
    
    def check_env(self):
        """Check if the virtual environment for flair is installed"""
        env_dir = os.path.join(self.plugin_dir,"flair_env")

        if os.name == 'nt':                                         #for windows
            python_exe = os.path.join(env_dir, "python.exe")
        else:                                                       #for mac linux
            python_exe = os.path.join(env_dir, "bin", "python")
            
        if os.path.exists(python_exe):
            return True
        else:
            return False
        
    def show_installation_dialog(self):
        self.install_dlg = InstallDialog()
        
        self.install_dlg.progress_bar.setRange(0, 0)
        self.install_dlg.progress_bar.setVisible(False)
        self.install_dlg.install_button.clicked.connect(self.start_installation_task)
        
        result = self.install_dlg.exec_()
        
        if result == 1:
            self.iface.messageBar().pushMessage("Success", "Environment ready. You can now use the plugin.", level=0)
        else:
            self.iface.messageBar().pushMessage("Error", "Installation failed. Check QGIS messages log.", level=2)

    def start_installation_task(self):
        self.install_dlg.install_button.setEnabled(False)
        self.install_dlg.progress_bar.setVisible(True)
        
        self.install_task = InstallEnv("Installing Conda Env...", self.plugin_dir, self.install_dlg)
        QgsApplication.taskManager().addTask(self.install_task)


    def run(self):
        if not self.check_env():
            is_installed = self.show_installation_dialog()
            if not is_installed:
                return 

        if self.first_start:
            self.first_start = False
            self.dlg = SemanticSegmentationDialog()

        if not self.dlg.exec_():
            return
        
        layer_name = self.dlg.comboBox.currentText()
        layers = QgsProject.instance().mapLayersByName(layer_name)
        if not layers:
            self.iface.messageBar().pushMessage("Error", "Selected layer not found", level=2)
            return
            
        input_img_path = layers[0].source()

        output_full_path = self.dlg.lineEdit.text()
        if not output_full_path:
            self.iface.messageBar().pushMessage("Error", "No output path specified", level=2)
            return
            
        output_path = os.path.dirname(output_full_path) + "/"
        output_name = os.path.basename(output_full_path)
        model_path = os.path.join(self.plugin_dir, "vendor", "FLAIR-INC_rgbi_15cl_resnet34-unet_weights.pth")

        config = {
            "output_path": output_path,
            "output_name": output_name,
            "input_img_path": input_img_path,
            "channels": [1, 2, 3, 4],
            "img_pixels_detection": 512,
            "margin": 128,
            "output_type": "argmax",
            "n_classes": 19,
            "model_weights": model_path,
            "model_framework": {
                "model_provider": "SegmentationModelsPytorch",
                "SegmentationModelsPytorch": {"encoder_decoder": "resnet34_unet"}
            },
            "batch_size": 4, 
            "use_gpu": False, 
            "num_worker": 0,
            "write_dataframe": False,
            "norma_task": [{
                "norm_type": "custom",
                "norm_means": [105.08, 110.87, 101.82, 106.38],
                "norm_stds": [52.17, 45.38, 44.00, 39.69]
            }]
        }

        temp_yaml_path = os.path.join(self.plugin_dir, "temp_config.yaml")
        with open(temp_yaml_path, 'w') as outfile:
            yaml.dump(config, outfile, default_flow_style=False)

        self.iface.messageBar().pushMessage("Success", f"Config saved: {temp_yaml_path}", level=0)

        env_dir = os.path.join(self.plugin_dir, "flair_env")
        python_exe = os.path.join(env_dir, "python.exe") if os.name == 'nt' else os.path.join(env_dir, "bin", "python3")
        script_path = os.path.join(self.plugin_dir, "vendor",'FLAIR-1', "src", "zone_detect", "main.py")
        
        if not os.path.exists(python_exe) or not os.path.exists(script_path):
            self.iface.messageBar().pushMessage("Error", "Python env or FLAIR script missing", level=2)
            return

        clr_file_path = os.path.join(self.plugin_dir, "color.clr")
        self.task = FlairInferenceTask(
            description="FLAIR Segmentation...",
            python_exe=python_exe,
            script_path=script_path,
            yaml_path=temp_yaml_path,
            output_tif=os.path.join(output_path, output_name),
            clr_path=clr_file_path,
            iface=self.iface
        )
        QgsApplication.taskManager().addTask(self.task)
        self.iface.messageBar().pushMessage("Info", "Analysis started in background", level=0)


class FlairInferenceTask(QgsTask):
    """Background task for FLAIR inference to keep QGIS responsive"""
    
    def __init__(self, description, python_exe, script_path, yaml_path, output_tif, clr_path,iface):
        super().__init__(description, QgsTask.CanCancel)
        self.python_exe = python_exe
        self.script_path = script_path
        self.yaml_path = yaml_path
        self.output_tif = output_tif
        self.iface = iface
        self.process = None
        self.clr_path = clr_path

    def run(self):
        try:
            clean_env = os.environ.copy()
            
            if 'LD_LIBRARY_PATH' in clean_env:
                del clean_env['LD_LIBRARY_PATH']
            if 'PYTHONPATH' in clean_env:
                del clean_env['PYTHONPATH']
            if 'PYTHONHOME' in clean_env:
                del clean_env['PYTHONHOME']

            flair_root = os.path.dirname(os.path.dirname(os.path.dirname(self.script_path)))

            self.process = subprocess.Popen(
                [self.python_exe, "-m", "src.zone_detect.main", f"--conf={self.yaml_path}"],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                cwd=flair_root,
                env=clean_env
            )

            for line in self.process.stdout:
                if self.isCanceled():
                    self.process.terminate()
                    return False
                QgsMessageLog.logMessage(line.strip(), "FLAIR", Qgis.Info)

            self.process.wait()
            
            if self.process.returncode == 0:
                return True
            else:
                return False
        except Exception as error_msg:
            QgsMessageLog.logMessage(str(error_msg), "FLAIR", Qgis.Critical)
            return False
    
    def finished(self, result):
        QgsMessageLog.logMessage("Finished method started", "FLAIR", Qgis.Info)
        
        if result == True:
            layer_name = os.path.basename(self.output_tif)
            layer = self.iface.addRasterLayer(self.output_tif, layer_name)
            
            if layer != None:
                if os.path.exists(self.clr_path):
                    self.apply_color_palette(layer)
                    
            self.iface.messageBar().pushMessage("Success", "Inference complete", level=Qgis.Success)
            
        if result == False:
            self.iface.messageBar().pushMessage("Error", "Task failed", level=Qgis.Critical)

    def apply_color_palette(self, layer):
        palette_classes = []
        
        with open(self.clr_path, 'r') as file:
            for line in file:
                parts = line.strip().split()
                if len(parts) >= 4:
                    pixel_value = int(parts[0])
                    red = int(parts[1])
                    green = int(parts[2])
                    blue = int(parts[3])
                    
                    color = QColor(red, green, blue)
                    palette_class = QgsPalettedRasterRenderer.Class(pixel_value, color, str(pixel_value))
                    palette_classes.append(palette_class)
        
        provider = layer.dataProvider()
        renderer = QgsPalettedRasterRenderer(provider, 1, palette_classes)
        layer.setRenderer(renderer)
        layer.triggerRepaint()
        self.iface.layerTreeView().refreshLayerSymbology(layer.id())


class InstallEnv(QgsTask):
    def __init__(self, description, plugin_dir, dialog):
        super().__init__(description, QgsTask.CanCancel)
        self.plugin_dir = plugin_dir
        self.dialog = dialog
    
    def run(self):
        try:
            setup_flair_environment(self.plugin_dir)
            return True
        except Exception as e:
            QgsMessageLog.logMessage(f"Install failed: {e}", "FLAIR", Qgis.Critical)
            return False

    def finished(self,result):
        if result:
            self.dialog.accept() 
        else:
            self.dialog.reject()