# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SemanticSegmentationDialog
                                 A QGIS plugin
 This plugin lets you create segmentation from aerial images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Kelian Pons
        email                : kelian.pons@centrale.centralelille.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsProject, QgsRasterLayer, QgsMapLayerProxyModel

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'semantic_segmentation_dialog_base.ui'))


class SemanticSegmentationDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(SemanticSegmentationDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.button_box.rejected.connect(self.reject)

        self.layer_combo_red.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.layer_combo_green.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.layer_combo_blue.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.layer_combo_nir.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.layer_combo_nir.setAllowEmptyLayer(True,"(Vide)")

        initial_layer_red = self.layer_combo_red.currentLayer()
        initial_layer_green = self.layer_combo_green.currentLayer()
        initial_layer_blue = self.layer_combo_blue.currentLayer()
        initial_layer_nir = None
        if initial_layer_red is not None:
            self.band_combo_red.setLayer(initial_layer_red)
        if initial_layer_green is not None:
            self.band_combo_green.setLayer(initial_layer_green)
        if initial_layer_blue is not None:
            self.band_combo_blue.setLayer(initial_layer_blue)
        if initial_layer_nir is not None:
            self.band_combo_nir.setLayer(initial_layer_nir)
        
        self.band_combo_nir.setShowNotSetOption(True,"(Vide)")
        self.layer_combo_red.layerChanged.connect(self.update_band_red)
        self.layer_combo_green.layerChanged.connect(self.update_band_green)
        self.layer_combo_blue.layerChanged.connect(self.update_band_blue)
        self.layer_combo_nir.layerChanged.connect(self.update_band_nir)

    def update_band_red(self, layer):
        if layer is not None:
            self.band_combo_red.setLayer(layer)

    def update_band_green(self, layer):
        if layer is not None:
            self.band_combo_green.setLayer(layer)

    def update_band_blue(self, layer):
        if layer is not None:
            self.band_combo_blue.setLayer(layer)

    def update_band_nir(self, layer):
        if layer is not None:
            self.band_combo_nir.setLayer(layer)


FORM_CLASS_INSTALL, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'install_dialog.ui'))

class InstallDialog(QtWidgets.QDialog, FORM_CLASS_INSTALL):
    def __init__(self, parent=None):
        """Constructor."""
        super(InstallDialog, self).__init__(parent)
        self.setupUi(self)
